### ISSUE TITLE
"roles-path" parameter should be facultative

### ISSUE THREAD

**Issue by nervo** [gantsign/alt-galaxy#24]
Just like this good old ansible-galaxy :)

**Comment by freemanjp** [comment]
I'm currently only using Ansible with Vagrant, and Vagrant always specifies the `roles-path`:
i.e. https://www.vagrantup.com/docs/provisioning/ansible_common.html#galaxy_command
e.g. https://github.com/gantsign/development-environment/blob/1.2.0/Vagrantfile#L280

Making `roles-path` facultative requires parsing the `ansible.cfg` (http://docs.ansible.com/ansible/galaxy.html#roles-path), which makes adding the feature a non-trivial task; given it's a feature I'm unlikely to use, for a temporary tool, with an easy workaround, I'm not going to implement this myself.

If you want to implement the feature, submit a pull request and I'm happy to review/merge it.

**Comment by nervo** [comment]
Hm, i was simply thinking about using a hard coded "/etc/ansible/roles" default value.

You're absolutly true about parsing the ansible.cfg, but maybe this can be implemented in a next (far) step ?

**Comment by freemanjp** [comment]
The problem with a partial implementation of this feature, is we'd be deliberately introducing a feature that would behave differently to `ansible-galaxy`, without resulting in an error when it's run.

It's exactly the sort of problem where an unsuspecting user could spend the best part of a day troubleshooting, wondering why the roles are being written to a different location than is specified by the `ansible.cfg`, before discovering it's non-complaint behaviour of the tool.

I think the risk in this case outweighs the benefit.

It's relatively easy to achieve the same result by wrapping your `alt-galaxy` invocation in a shell script \ shell function if this is important to you.

**Comment by nervo** [comment]
It's not :)
