### ISSUE TITLE
Support dependencies versions

### ISSUE THREAD

**Issue by nervo** [gantsign/alt-galaxy#26]
This commit (https://github.com/gantsign/alt-galaxy/pull/23/commits/eae00f3bdf0cf41c87dd154f5697ece7551dae97) introduce the support for roles dependencies, that is great \o/

Btw, the official syntax also support version, such as:
```
- role: foo.bar,1.0.0
```

**Comment by freemanjp** [comment]
Version support should have been implemented with dependency support but it was missing from the documentation: https://galaxy.ansible.com/intro#meta

**Comment by freemanjp** [comment]
@nervo: thanks for the feedback; the bug fixes / enhancements you identified are now available in version [1.2.0](https://github.com/gantsign/alt-galaxy/releases/tag/1.2.0).

**Comment by nervo** [comment]
Dude, i was just about to submit my second pull request of my life in go lang :)

**Comment by freemanjp** [comment]
Sorry dude, next time let me know :)
